// Command gen-unihan parses the Unicode Unihan_Readings.txt data file and
// emits Go source for the per-codepoint Mandarin (tonal pinyin) and
// Cantonese (Jyutping) reading tables.
//
// Usage:
//
//	go run ./internal/cmd/gen-unihan -in /tmp/unihan/Unihan_Readings.txt
//
// Source: https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip
// License: Unicode Terms of Use (https://www.unicode.org/copyright.html).
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	in := flag.String("in", "/tmp/unihan/Unihan_Readings.txt", "path to Unihan_Readings.txt")
	haniOut := flag.String("hani-out", "languages/hani/table.go", "output path for Mandarin pinyin table")
	yuehOut := flag.String("yueh-out", "languages/yueh/table.go", "output path for Cantonese Jyutping table")
	flag.Parse()

	mandarin, cantonese, err := parseUnihan(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "parse:", err)
		os.Exit(1)
	}

	if err := writeTable(*haniOut, "hani", "generatedTonalMap",
		"Mandarin (Hanyu Pinyin, tone-marked)",
		"kMandarin field of the Unicode Unihan Database.",
		mandarin); err != nil {
		fmt.Fprintln(os.Stderr, "hani:", err)
		os.Exit(1)
	}

	if err := writeTable(*yuehOut, "yueh", "generatedJyutpingMap",
		"Cantonese (Jyutping, tone digit appended)",
		"kCantonese field of the Unicode Unihan Database.",
		cantonese); err != nil {
		fmt.Fprintln(os.Stderr, "yueh:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d Mandarin readings to %s\n", len(mandarin), *haniOut)
	fmt.Printf("wrote %d Cantonese readings to %s\n", len(cantonese), *yuehOut)
}

// parseUnihan extracts kMandarin and kCantonese readings for each
// codepoint. For kMandarin, only the first reading is kept when multiple
// are listed (space-separated). kCantonese has a single reading per row.
func parseUnihan(path string) (mand, cant map[rune]string, err error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()

	mand = make(map[rune]string, 50_000)
	cant = make(map[rune]string, 30_000)

	s := bufio.NewScanner(f)
	s.Buffer(make([]byte, 64*1024), 1<<20)
	for s.Scan() {
		line := s.Text()
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) != 3 {
			continue
		}
		cp, ok := parseCodepoint(parts[0])
		if !ok {
			continue
		}
		// We only care about CJK Unified Ideographs U+4E00..U+9FFF for
		// the current packages. Extension blocks (A, B, C, ...) are not
		// in scope.
		if cp < 0x4E00 || cp > 0x9FFF {
			continue
		}
		switch parts[1] {
		case "kMandarin":
			r := firstReading(parts[2])
			if r != "" {
				mand[cp] = r
			}
		case "kCantonese":
			r := firstReading(parts[2])
			if r != "" {
				cant[cp] = r
			}
		}
	}
	return mand, cant, s.Err()
}

func parseCodepoint(s string) (rune, bool) {
	if !strings.HasPrefix(s, "U+") {
		return 0, false
	}
	n, err := strconv.ParseInt(s[2:], 16, 32)
	if err != nil {
		return 0, false
	}
	return rune(n), true
}

func firstReading(s string) string {
	if i := strings.IndexByte(s, ' '); i >= 0 {
		return s[:i]
	}
	return s
}

func writeTable(path, pkg, mapName, what, source string, m map[rune]string) error {
	out, err := os.Create(path)
	if err != nil {
		return err
	}
	defer out.Close()

	bw := bufio.NewWriter(out)
	fmt.Fprintf(bw, "// Code generated by internal/cmd/gen-unihan. DO NOT EDIT.\n")
	fmt.Fprintf(bw, "// %s for the CJK Unified Ideographs block (U+4E00..U+9FFF),\n", what)
	fmt.Fprintf(bw, "// derived from the %s\n", source)
	fmt.Fprintf(bw, "\npackage %s\n\n", pkg)
	fmt.Fprintf(bw, "var %s = map[rune]string{\n", mapName)

	codes := make([]rune, 0, len(m))
	for cp := range m {
		codes = append(codes, cp)
	}
	sort.Slice(codes, func(i, j int) bool { return codes[i] < codes[j] })

	for _, cp := range codes {
		fmt.Fprintf(bw, "\t0x%04X: %q,\n", cp, m[cp])
	}
	fmt.Fprintf(bw, "}\n")
	return bw.Flush()
}
